### PR TITLE
Support batching

### LINKED ISSUE #15: Batch contributions for the same reporting origin together
The report scheme permits multiple contributions in the same report. We should consolidate some histogram contributions to reduce the volume of reports. For example, calls to sendHistogramReport() during the same Shared Storage operation could be batched together.

### PR DESCRIPTION
**Pull request by alexmturner**
Resolves #15

### CODE REVIEW

**Comment by alexmturner** [comment]
@johnivel @csharrison could you PTAL (in particular at the suggested batching scopes)? Thanks!

**Review by johnivdel — APPROVED** [review]
LGTM

**Comment by johnivdel** [comment]
It might worth pointing out something about the size of reports leaking information, which necessitates padding / etc

**Comment by alexmturner** [comment]
Added a comment

**Pull request merged**
