### PR TITLE
Remove patches to Private Aggregation since they got incorprorated there.

### PR DESCRIPTION
**Pull request by morlovich**
See https://github.com/WICG/turtledove/pull/1297 and https://github.com/WICG/turtledove/pull/1312

***
<a href="https://pr-preview.s3.amazonaws.com/morlovich/private-aggregation-api/pull/166.html" title="Last updated on Nov 4, 2024, 2:07 PM UTC (d4d6a5d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/166/d98b3fc...morlovich:d4d6a5d.html" title="Last updated on Nov 4, 2024, 2:07 PM UTC (d4d6a5d)">Diff</a>

### CODE REVIEW

**Comment by morlovich** [comment]
Hi @alexmturner, could you perhaps review this? It's the mirror of the other change..

**Review by alexmturner — APPROVED** [review]

**Comment by alexmturner** [comment]
Unfortunately, this seems to have a couple compiling issues, due to the following not being defined/exported any more:
- [=interest group/Private Aggregation coordinator=]
- [=auction config/seller Private Aggregation coordinator=]
- [=auction config/auction report buyers=]
- [=auction config/auction report buyer keys=]
- [=auction config/auction report buyer debug details=]

Maybe we keep these defined in the spec temporarily just to avoid the errors?

It's also complaining about having multiple definitions for:
- {{AuctionReportBuyersConfig/bucket}}
- {{AuctionReportBuyersConfig/scale}}

but I think that must just be caching issue? You removed those definitions in this pr...

**Comment by morlovich** [comment]
Huh, did something happen with our auction config/interest group exports? Investigating.

**Comment by alexmturner** [comment]
I think the auction config/interest group pieces were defined in this spec so they didn't need to be exported. But they're still used in the remaining monkey patches. Alternatively, we could modify them to e.g. `<a spec="turtledove" for="auction config">auction report buyers</a>`, but that seems maybe laborious

**Comment by morlovich** [comment]
> I think the auction config/interest group pieces were defined in this spec so they didn't need to be exported. But they're still used in the remaining monkey patches. Alternatively, we could modify them to e.g. `<a spec="turtledove" for="auction config">auction report buyers</a>`, but that seems maybe laborious

Probably not worth the effort since they should be going away shortly.

**Comment by alexmturner** [comment]
Yeah, agreed -- probably easiest to just revert the changes under the "Structures" heading for now.

**Comment by morlovich** [comment]
PTAL --- updated to just remove the entire section.

**Comment by alexmturner** [comment]
SLGTM, thanks!

**Pull request merged**
